Algoritmo "ExercicioL04G - Repita "
// Disciplina   : Lógica de Programação Em JavaScript
// Professor   : Jailson Santos
// Descrição   : Elaborar um programa que apresente como resultado
// o valor do fatorial dos valores ímpares situados na faixa numérica
//  de 1 a 10.
// Autor(a)    : Julio Cardoso Ambrósio
// Data atual  : 25/09/2024

Var


Inicio

repita




      repita


      ate

escreval("")
ate



Fimalgoritmo