Algoritmo "ExercicioL05C - Para"
// Disciplina  : [Lógica de Programação em JavaScript]
// Professor   : Jailson Santos
// Descrição   :  Apresentar o total da soma obtida dos
// cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Julio Cardoso Ambrósio
// Data atual  : 29/08/2024
Var
   soma, i: inteiro
Inicio

   Para i de 1 ate 100 faca
      soma <- soma + i
   Fimpara
   escreval(" O resultado da soma dos 100 primeiros números é: ", soma)
Fimalgoritmo