Algoritmo "ExercicioL05A - Para"
// Disciplina  : [Lógica de Programação em JavaScript]
// Professor   : Jailson Santos
// Descrição   :  Apresentar os quadrados dos números inteiros de 15
// a 200.
// Autor(a)    : Julio Cardoso Ambrósio
// Data atual  : 29/08/2024
Var
   numero, quadrado: inteiro
Inicio
   Para num de 15 ate 200 faca
      quadrado <- num * num
      escreval("O quadrado de ", num, " é: ", quadrado)
   Fimpara
Fimalgoritmo
